config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_url, notice: "タスク「#{task.name}」を登録しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskliaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf
    .container
    = yield

app/views/tasks/edit.html.slim
h1 Tasks#edit
p Find me in app/views/tasks/edit.html.slim

app/views/tasks/index.html.slim
td = link_to task.name, task

= link_to  "新規登録", new_task_path, class: 'btn btn-primary' 

app/views/tasks/new.html.slim
h1 タスク新規登録

.nav.justify-content-end
 = link_to '一覧', tasks_path, class: 'nav-link'

= form_with model: @task, local: true do |f|
    .form-group
     = f.label :name
     = f.text_field :name, class: 'form-control', id: 'task_name'
    .form-group
     = f.label :description
     = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
     = f.submit nil, class: 'btn btn-primary'

app/views/tasks/show.html.slim
h1 Tasks#show
p Find me in app/views/tasks/show.html.slim